"""Add cascade delete for notifications and set null for activity_logs

Revision ID: ab201d8b3d6f
Revises: 
Create Date: 2026-01-07 12:20:08.669804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab201d8b3d6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_logs_action', table_name='activity_logs')
    op.drop_index('idx_activity_logs_category', table_name='activity_logs')
    op.drop_index('idx_activity_logs_created_at', table_name='activity_logs')
    op.drop_constraint('activity_logs_user_id_fkey', 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('email_settings', 'smtp_host',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('email_settings', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('email_settings', 'smtp_username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('email_settings', 'smtp_password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('email_settings', 'from_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('idx_ip_allocations_peer_id', table_name='ip_allocations')
    op.drop_index('idx_ip_allocations_status', table_name='ip_allocations')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_index('idx_notifications_read', table_name='notifications')
    # Add CASCADE DELETE for notifications
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_peer_handshakes_event_time', table_name='peer_handshakes')
    op.drop_index('idx_peer_keys_public_key', table_name='peer_keys')
    op.drop_index('idx_peer_metadata_group', table_name='peer_metadata')
    op.create_index(op.f('ix_peer_metadata_expires_at'), 'peer_metadata', ['expires_at'], unique=False)
    op.create_index('ix_peer_metadata_expiry', 'peer_metadata', ['expires_at', 'expired_notified'], unique=False)
    op.drop_index('idx_sessions_expires_at', table_name='sessions')
    op.drop_index('idx_sessions_session_token', table_name='sessions')
    op.alter_column('telegram_notification_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('telegram_notification_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_telegram_logs_category', table_name='telegram_notification_logs')
    op.drop_index('idx_telegram_logs_created_at', table_name='telegram_notification_logs')
    op.drop_index('idx_telegram_logs_interface', table_name='telegram_notification_logs')
    op.drop_index('idx_telegram_logs_peer_id', table_name='telegram_notification_logs')
    op.drop_index('idx_telegram_logs_success', table_name='telegram_notification_logs')
    op.drop_index('idx_telegram_logs_user_id', table_name='telegram_notification_logs')
    op.create_index(op.f('ix_telegram_notification_logs_category'), 'telegram_notification_logs', ['category'], unique=False)
    op.create_index(op.f('ix_telegram_notification_logs_created_at'), 'telegram_notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_telegram_notification_logs_id'), 'telegram_notification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_notification_logs_interface_name'), 'telegram_notification_logs', ['interface_name'], unique=False)
    op.create_index(op.f('ix_telegram_notification_logs_peer_id'), 'telegram_notification_logs', ['peer_id'], unique=False)
    op.create_index(op.f('ix_telegram_notification_logs_user_id'), 'telegram_notification_logs', ['user_id'], unique=False)
    op.alter_column('telegram_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('telegram_settings', 'notification_categories',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('telegram_settings', 'test_message_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('telegram_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_telegram_settings_enabled', table_name='telegram_settings')
    op.create_index(op.f('ix_telegram_settings_id'), 'telegram_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_settings_id'), table_name='telegram_settings')
    op.create_index('idx_telegram_settings_enabled', 'telegram_settings', ['enabled'], unique=False)
    op.alter_column('telegram_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('telegram_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('telegram_settings', 'test_message_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('telegram_settings', 'notification_categories',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('telegram_settings', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_telegram_notification_logs_user_id'), table_name='telegram_notification_logs')
    op.drop_index(op.f('ix_telegram_notification_logs_peer_id'), table_name='telegram_notification_logs')
    op.drop_index(op.f('ix_telegram_notification_logs_interface_name'), table_name='telegram_notification_logs')
    op.drop_index(op.f('ix_telegram_notification_logs_id'), table_name='telegram_notification_logs')
    op.drop_index(op.f('ix_telegram_notification_logs_created_at'), table_name='telegram_notification_logs')
    op.drop_index(op.f('ix_telegram_notification_logs_category'), table_name='telegram_notification_logs')
    op.create_index('idx_telegram_logs_user_id', 'telegram_notification_logs', ['user_id'], unique=False)
    op.create_index('idx_telegram_logs_success', 'telegram_notification_logs', ['success'], unique=False)
    op.create_index('idx_telegram_logs_peer_id', 'telegram_notification_logs', ['peer_id'], unique=False)
    op.create_index('idx_telegram_logs_interface', 'telegram_notification_logs', ['interface_name'], unique=False)
    op.create_index('idx_telegram_logs_created_at', 'telegram_notification_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_telegram_logs_category', 'telegram_notification_logs', ['category'], unique=False)
    op.alter_column('telegram_notification_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('telegram_notification_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('idx_sessions_session_token', 'sessions', ['session_token'], unique=False)
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.drop_index('ix_peer_metadata_expiry', table_name='peer_metadata')
    op.drop_index(op.f('ix_peer_metadata_expires_at'), table_name='peer_metadata')
    op.create_index('idx_peer_metadata_group', 'peer_metadata', ['group_name'], unique=False)
    op.create_index('idx_peer_keys_public_key', 'peer_keys', ['public_key'], unique=False)
    op.create_index('idx_peer_handshakes_event_time', 'peer_handshakes', [sa.text('event_time DESC')], unique=False)
    # Revert CASCADE DELETE for notifications
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.create_index('idx_notifications_read', 'notifications', ['read'], unique=False)
    op.create_index('idx_notifications_created_at', 'notifications', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_ip_allocations_status', 'ip_allocations', ['status'], unique=False)
    op.create_index('idx_ip_allocations_peer_id', 'ip_allocations', ['peer_id'], unique=False)
    op.alter_column('email_settings', 'from_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_settings', 'smtp_password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('email_settings', 'smtp_username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('email_settings', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('email_settings', 'smtp_host',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key('activity_logs_user_id_fkey', 'activity_logs', 'users', ['user_id'], ['id'])
    op.create_index('idx_activity_logs_created_at', 'activity_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_activity_logs_category', 'activity_logs', ['category'], unique=False)
    op.create_index('idx_activity_logs_action', 'activity_logs', ['action'], unique=False)
    # ### end Alembic commands ###
